--- 
- name: Configure device credentials on Cisco DNA Center
  hosts: dnac_servers
  vars_files:
    - "credentials.yml"
    - "input.yml"
  connection: local
  gather_facts: no
  tasks:
    - name: Get Device info and updating access point details
      cisco.dnac.accesspoint_workflow_manager:
        device_fields: "{{device_fields}}"
        ap_selected_field: "{{ap_selected_field}}"
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log: True
        dnac_log_level: DEBUG
        config_verify: True
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        config: "{{ config }}"
      register: output_list
