---
device_fields: "id,family,type,macaddress,managementipaddress"
ap_selected_field: "instanceid,displayname,internalkey,macaddress,radiodtos"
device_filterfield: "hostname,macaddress"
device_filter_string: "sw2,sw1|52:54:00:0e:1c:6a"
display_selection: 1

config:
    - macaddress: "52:54:00:0f:25:4c"
      managementipaddress: "10.10.20.178"
      accesspointradiotype: 1
      apname: "HallAP"
    - macaddress: "52:54:00:0e:1c:6a"
      managementipaddress: "10.10.20.176"
      accesspointradiotype: 2
      apname: "FloorAP"
    - macaddress: "52:54:00:0e:1c:6a"
      managementipaddress: "10.10.20.176"
      accesspointradiotype: 3
      apname: "MeetingRoomAP"
    - macaddress: "52:54:00:0e:1c:6a"
      managementipaddress: "10.10.20.176"
      accesspointradiotype: 6
      apname: "MeetingRoom2AP"
